### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by AliBi2000** [Bombaba/BlenderPythonScripts#4] opened 2016-06-19 12:44 UTC
Loading in the script as an addon works fine but blender always crashes as soon as im trying to use the offset any edge. There is (most times) no error message blender simply closes. I managed to screenshot this error message. I hope you know what is wrong or have i maybe done somthing wrong whilst installing it?
![error_msg](https://cloud.githubusercontent.com/assets/20026959/16177401/5a3b93a0-362c-11e6-89ea-993e98841d05.png)

**Comment by Bombaba** [comment] 2016-06-30 16:21
I'm really sorry for your inconvenience...
Does this error occur every time you use the offset addon?
Would you mind uploading the blend file for me to reproduce the error?

**Comment by ahlwong** [comment] 2016-07-24 22:42
I have the same issue on Blender 2.77a running on OSX.
<img width="848" alt="screen shot 2016-07-24 at 3 40 58 pm" src="https://cloud.githubusercontent.com/assets/1441263/17087003/0a6d3bf4-51b5-11e6-8100-b0ce3746db3a.png">

I have uploaded my file here: http://www.aw-industries.com/Files/offset-edge-crash.blend

**Comment by Bombaba** [comment] 2016-07-25 05:11
@ahlwong 
I couldn't reproduce the error using your file.
Does this error occur every time you use this addon? 
I'm interested in the situation under which this error occured (especially mouse position), because the functional part of this error is for detecting mouse position inside the 3d window.

**Comment by Bombaba** [comment] 2016-07-25 05:28
For the moment, you can turn off the interactive feature of this addon from preference window.
Turning off this option will prevent the error.
![offset_edges_interactive](https://cloud.githubusercontent.com/assets/5233867/17091293/1733a944-5274-11e6-85c3-baae5db12c7c.jpg)

**Comment by ahlwong** [comment] 2016-07-25 05:52
Thanks for your reply.

Yes, it happens every time and for all options (extrude, move, etc...).

If I turn off interactive mode it works as you suspected.

Here's a video of the crash: http://www.aw-industries.com/Files/offset-edge-crash.mov

**Comment by Bombaba** [comment] 2016-07-25 07:16
Ok, I found out the cause of crash.

I'll fix this issue ASAP, but it may take some time.
If you execute this addon from the edge menu inside the 3d window(CTRL-E), you can use it without error even with interactive option on.

**Comment by Bombaba** [comment] 2016-07-25 08:13
Fixed this bug.
Probably you can use this addon safely with interactive mode on, so please try it.
If you don't meet the crash, I will close this issue.

**Comment by ahlwong** [comment] 2016-07-25 20:13
Yes, that fixed it!

Thank you for the quick fix and for your script. It's going to be super useful.

**Comment by Bombaba** [comment] 2016-07-26 02:29
You are welcome.
Thank you for your bug report.

**Closed as completed by Bombaba** 2016-07-26 02:29 UTC
